### ISSUE TITLE
[Feature] Prevent parallel jobs

### ISSUE THREAD

**Issue by frankhaugen** [logiqsystem/cronquery#24] opened 2020-07-02 09:04 UTC
Sometimes a job should run really often but never in parallel. I've discovered that DB-calls fail because some long-running processes overlap. So a flag in configuration to be "RunInParallel" could be advantageous.

**Comment by marxjmoura** [comment] 2020-07-02 11:04
How about workflows? Workflows run in parallel, but the jobs that make up that workflow will always run in sequence.

```json
{
  "CronQuery": {
    "Running": true,
    "TimeZone": "E. South America Standard Time",
    "Workflows": [
      {
        "Running": true,
        "Jobs": [
          {
            "Name": "MyFirstJob",
            "Running": true,
            "Cron": "* * * * * 1-6"
          },
          {
            "Name": "MySecondJob",
            "Running": true,
            "Cron": "0 0 2 * * *"
          },
          {
            "Name": "MyThirdJob",
            "Running": true,
            "Cron": "* * 14-18 * * 6/15"
          }
        ]
      }
    ]
  }
}
```

**Comment by frankhaugen** [comment] 2020-07-02 11:37
I love the idea of workflows!

Will a workflow run to completion before re-triggering? (And maybe a workflow could be triggered by a cron-query?)

Here's one of my scenarios:
every minute I check an email-inbox to see if there are any new emails, if there are, these are collected and processed. Since most emails coming in have attachments, this can take some time, and if there happens to be a lot of emails, the job easily takes more than a minute, which means that the job will re-run and both the email and SQL server starts complaining about open connections.

The scenario is currently being run with a HostedService with logic inside a while-loop with a Task-Delay of 60 seconds, so it doesn't parallel, but this has had some issues with memory consumption. Tests using CronQuery has improved things a lot, until it picks up 100+ emails with an avarage size above 2.5MB in one go, (which is pretty common in our system at particular times of day)

**Comment by marxjmoura** [comment] 2020-07-02 12:17
Good to know that you liked the idea. :)

Sorry, I basically copied and pasted. A cron trigger for each job can easily break the sequence. In fact, a workflow must be completed before it can be triggered again, as you said. This is the correct configuration:

```json
"Workflows": [
  {
    "Cron": "* * * * * 1-6",
    "Running": true,
    "Jobs": [
      {
        "Name": "MyFirstJob",
        "Running": true
      },
      {
        "Name": "MySecondJob",
        "Running": true
      },
      {
        "Name": "MyThirdJob",
        "Running": true
      }
    ]
  }
]
```

Still, there is something about your scenario that caught my attention, if I understand correctly. By design, Cronquery should not start a new instance of a job that is still running. If that's the case, I will need to investigate.

**Comment by frankhaugen** [comment] 2020-07-02 19:39
>By design, Cronquery should not start a new instance of a job that is still running

That's strange. Then it might be some threading issue in my code, where something gets executed in parallel, or a Task, even when awaited, don't behave as expected due to some third party library.

**Comment by marxjmoura** [comment] 2020-07-02 21:46
Please, let know if your suspicion is confirmed. Remember that jobs must be triggered by CronQuery.

Also, I have thinking about the workflow idea. Workflows does not bring benefits to justify the effort. We can call private methods or methods of other objects in sequence as job steps.

**Comment by frankhaugen** [comment] 2020-07-03 11:34
I also had a look at the possibility of workflows, and your point about that it's not really beneficial. Your suggested way is better.

Went completely crazy and started an extra slow job, (I made it slow on purpose, doing crazy things like reading and writing to files above 100MB both async and sync), every second, and compared it it a simple empty Job, only containing a Task.Delay.

It's seems to be "safe", so my original scenario has most likely something weird going on with external dependencies, because if everything is contained in the job/application I cannot replicate it

I'm having a few weeks off work now, so I might be improving the Wiki/docs, (no promises), to make this subtle "feature" of jobs not going in parallel a bit more clear; if you don't mind?

Thank you for all your input :-)

**Comment by marxjmoura** [comment] 2020-07-03 17:57
Thank you for taking the time to investigate. Feel free to edit, no worries. :)

**Comment by marxjmoura** [comment] 2020-07-17 12:57
I'm closing this issue. Feel free to open a new one at any time.

**Closed as completed by marxjmoura** 2020-07-17 12:57 UTC
Labels: help wanted
